### ISSUE TITLE
What are the features we should include? 

### ISSUE THREAD

**Issue by malinPera** [malinPera/CO328-project#1]

**Comment by nathasha-naranpanawa** [comment]
mainly we might need flashcards option. Then we can also have another technique which give definitions so that user can learn by providing the correct word.

**Comment by buddhiW** [comment]
Any person should be able to create a course. Person who created the course must decide the privacy of the course (shared or private). Main attributes of a course would be course code, name, date initiated, privacy, description, teacher of the course.

A shared course needs to have a list of subscribers as an attribute.

Some of the basic learning tools that can be included are flash cards, multiple choice questions and structured questions.
